### ISSUE TITLE
Change renaming strategy

### ISSUE THREAD

**Issue by elidupuis** [elidupuis/ember-cli-deploy-archive#8]
Instead of outright moving the `deploy-dist` directory, simply copy it and then delete it. Probably better to leave the `deploy-dist` directory untouched.

https://github.com/elidupuis/ember-cli-deploy-archive/blob/master/index.js#L70

**Comment by rstudner** [comment]
Interestingly, on CircleCI I can't set packedDirName to "anything" and have it work.

Wondering if this change will help.

```
node_modules/ember-cli/bin/ember deploy development
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
bootstrap-sassy config: no JS enabled, glyphicons enabled
Deploying [>---] 25% [plugin: build -> build]cleaning up
cleaning up...
- moving tmp/deploy-dist to tmp/my-ui
Deploying [=>--] 50% [plugin: archive -> didBuild]- saving tarball of tmp/my-ui to ui.tar.gz
- tarball ok
- Error: Cannot use simple-git on a directory that does not exist.
Error: Cannot use simple-git on a directory that does not exist.
Error: Cannot use simple-git on a directory that does not exist.
    at module.exports (/home/ubuntu/ember-ui/node_modules/simple-git/src/index.js:11:15)
    at /home/ubuntu/ember-ui/node_modules/ember-cli-deploy-revision-data/lib/scm-data-generators/git.js:15:7
    at initializePromise (/home/ubuntu/ember-ui/node_modules/rsvp/dist/rsvp.js:588:5)
    at PromiseExt.Promise (/home/ubuntu/ember-ui/node_modules/rsvp/dist/rsvp.js:1076:31)
    at new PromiseExt (/home/ubuntu/ember-ui/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at CoreObject.generate (/home/ubuntu/ember-ui/node_modules/ember-cli-deploy-revision-data/lib/scm-data-generators/git.js:14:12)
    at Class._getScmData (/home/ubuntu/ember-ui/node_modules/ember-cli-deploy-revision-data/index.js:66:45)
    at Class.prepare (/home/ubuntu/ember-ui/node_modules/ember-cli-deploy-revision-data/index.js:37:23)
    at Object.fn (/home/ubuntu/ember-ui/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/home/ubuntu/ember-ui/node_modules/ember-cli-deploy/lib/models/pipeline.js:175:19)
    at tryCatch (/home/ubuntu/ember-ui/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/ubuntu/ember-ui/node_modules/rsvp/dist/rsvp.js:553:13)
    at /home/ubuntu/ember-ui/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/home/ubuntu/ember-ui/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)Pipeline aborted

node_modules/ember-cli/bin/ember deploy development returned exit code 1

Action failed: node_modules/ember-cli/bin/ember deploy development
```

**Comment by rstudner** [comment]
I was actually trying to set packedDirName to '' or something.. my goal is I was my build.tar.gz to have NO nested folder -- and I can't seem to get that to work.

(by default it is deploy-dist/ etc)

**Comment by elidupuis** [comment]
Hi Roger, 

I recognize that error `Cannot use simple-git on a directory that does not exist.`. I believe it's related to a new version of `git-repo-info`. I fixed this recently by bumping `ember-cli-deploy-revision-data` to 0.3.2; see https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/41.

You may also have to update the `revision-data` config to include `distDir` if you haven't already: https://github.com/showbie/ember-cli-deploy-showbie-pack/pull/1/files#diff-b977fae3e2dff7252ee5f7b3be2000f1R38
